### ISSUE TITLE
WANT: Single Binary

### ISSUE THREAD

**Issue by manabuishii** [tom-tan/zatsu-cwl-generator#12]
If single binary is provided, more easy to execute.

**Comment by tom-tan** [comment]
Currently I try to construct a cross compile environment based on [dlang2/ldc-ubuntu docker image](https://hub.docker.com/r/dlang2/ldc-ubuntu).

I expect that it will be done by using [ldc-build-runtime](https://wiki.dlang.org/Building_LDC_runtime_libraries) but I failed to build the environment...

**Comment by tom-tan** [comment]
Here is a list to close this issue:

- [x] prepare a build environment for static linked binary
  - Now we can easily make It by using remote container extension of VSCode
- [ ] Add the static linked binary in the release page
- [ ] Provide a container for zatsu_cwl_generator

**Comment by tom-tan** [comment]
Now you can get the binary from the [CI page](https://github.com/tom-tan/zatsu-cwl-generator/actions) or use [ttanjo/zatsu-cwl-generator](https://hub.docker.com/r/ttanjo/zatsu-cwl-generator) image.
