### ISSUE TITLE
WANT: Container

### ISSUE THREAD

**Issue by manabuishii** [tom-tan/zatsu-cwl-generator#13]
It's helpful if there are some containers (Docker , Singularity,,,,)

**Comment by tom-tan** [comment]
It can be done by generating the following, for example:

```cwl
hints:
  - class: DockerRequirement
    dockerPull: alpine:latest
```

The main problem is how to choose an appropriate containers from the given command.

One option is to use [biocontainers](https://biocontainers.pro/#/) but it does not provide a way to search for containers that contains specific command...

Another option is to provide a way for users to specify the container like:
```console
$ ./zatsu_cwl_generator.d "echo aaa bbb > out.txt" --conainer="alpine:latest"
```
But I do not want to introduce options if possible...
