### ISSUE TITLE
WANT: Display zatsu-cwl-generator version

### ISSUE THREAD

**Issue by manabuishii** [tom-tan/zatsu-cwl-generator#15]
I think it is helpful if zatsu-cwl-generator version to miscommunication.

For example
```console
$ ./zatsu-cwl-generator.d
Version: 1.0.0
```

**Comment by tom-tan** [comment]
Now it generates version string and can be downloaded from the [release page](https://github.com/tom-tan/zatsu-cwl-generator/releases/latest)!

```console
$ ./zatsu-cwl-generator.d
zatsu-cwl-generator v1.0.0
Usage: zatsu-cwl-generator <commandline>
```
